language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=RelWithDebInfo
  - CONFIGURATION=MinSizeRel
  - CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ../test
  - make
  - ./process_test
